global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

scrape_configs:
  - job_name: "REST"
    static_configs:
      - targets: ["app:8000"]
  - job_name: "gRPC"
    static_configs:
      - targets: ["grpc:8001"]
  - job_name: "websocket"
    static_configs:
      - targets: ["websocket:8002"]
