services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rest.production
    ports:
      - 8000:8000
    volumes:
      - data:/data
    restart: unless-stopped
    depends_on:
      - postgres
  grpc:
    build:
      context: ..
      dockerfile: docker/Dockerfile.grpc.production
    ports:
      - 50051:50051
      - 8001:8001
    volumes:
      - data:/data
    restart: unless-stopped
    depends_on:
      - postgres
  websocket:
    build:
      context: ..
      dockerfile: docker/Dockerfile.websocket.production
    ports:
      - 5000:5000
      - 8002:8002
    volumes:
      - data:/data
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: glossary
      POSTGRES_USER: glossary
      POSTGRES_PASSWORD: glossary
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus:v3.7.3
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:12.1
    ports:
      - 3333:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  data:
  grafana_data:
  prometheus_data:
  postgres_data:
